# Generated by Django 3.2.7 on 2021-10-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('oik', models.CharField(max_length=100)),
                ('tik', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('total_voters', models.IntegerField(default=0)),
                ('ballots_recieved', models.IntegerField(default=0)),
                ('ballots_ahead', models.IntegerField(default=0)),
                ('ballots_out', models.IntegerField(default=0)),
                ('ballots_in', models.IntegerField(default=0)),
                ('ballots_destroyed', models.IntegerField(default=0)),
                ('ballots_collected_out', models.IntegerField(default=0)),
                ('ballots_collected_in', models.IntegerField(default=0)),
                ('ballots_spoiled', models.IntegerField(default=0)),
                ('ballots_ok', models.IntegerField(default=0)),
                ('ballots_lost', models.IntegerField(default=0)),
                ('ballots_excess', models.IntegerField(default=0)),
                ('kprf', models.IntegerField(default=0)),
                ('green', models.IntegerField(default=0)),
                ('ldpr', models.IntegerField(default=0)),
                ('new_people', models.IntegerField(default=0)),
                ('er', models.IntegerField(default=0)),
                ('sr', models.IntegerField(default=0)),
                ('apple', models.IntegerField(default=0)),
                ('rost', models.IntegerField(default=0)),
                ('rpss', models.IntegerField(default=0)),
                ('kpkr', models.IntegerField(default=0)),
                ('platform', models.IntegerField(default=0)),
                ('green_alternative', models.IntegerField(default=0)),
                ('motherland', models.IntegerField(default=0)),
                ('retired', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
